apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  users.anonymous.enabled: "true"

  kustomize.version.4.4.1: /usr/local/bin/kustomize

  application.instanceLabelKey: argocd.aws-dev.kromanow94-dev.com/appname
